First working iteration. No Tests.
Dronch/GameLifeCSharpConsole pull request #1
Opened 2020-01-06 19:12 UTC by kismetd

Игровая логика пока работает неправильно, кажется.

2020-01-06 21:21 UTC, Dronch commented on Program.cs
> +            while (field.AreAllCellsDead() && Console.KeyAvailable == false);
Хорошая идея останавливать игру когда поле пустеет

2020-01-06 23:04 UTC, Dronch requested changes
1) Хороший стиль нэйминга и структурирования кода. Чтобы упростить жизнь, можно обратить внимания на инструменты, помогающие соблюдать хороший стиль, например: https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2017
2) Если кажется, что задача типичная и ее уже решали многие разработчики, то лучше прогуглить и не изобретать велосипед (с опытом появится скилл задавать правильные вопросы гуглу). https://www.google.com/search?q=c+sharp+string+of+repeating+characters
3) Обход двухмерного массива имеет сложность O(width*height), поэтому если есть возможность, с точки зрения производительности, его лучше проходить как можно меньше раз.
4) Стоит обратить внимание на исключения. Ловить абсолютно все исключения в блоке try - плохой тон, поэтому нужно их кастомизировать. https://docs.microsoft.com/ru-ru/dotnet/standard/exceptions/best-practices-for-exceptions

2020-01-06 23:04 UTC, Dronch commented on cell.cs
> +        }
Можем ли мы использовать более лаконичную запись для конструктора с одним аргументом?
Например
`public Cell(bool isActive) => WillBeActive = isActive;`

2020-01-06 23:04 UTC, Dronch commented on cell.cs
> +        }
Можно ли улучшить читаемость этого фрагмента?
Например, для сложных условных операций можно ввести дополнительные булевые переменные:
```
bool will_born = !IsActive && activeNeighbors == 3;
if (will_born) {}
```

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +            _height = height; //y (i)
Если удобнее использовать x и y, то чтобы не путаться, может стоит их и использовать вместо i, j?

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +            CheckActiveInputCells(rows);
Хорошая идея - разделить валидацию входных данных на подзадачи.

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                    DrawUpperBorderLine();
Если это вынести перед циклом, тогда и иф не нужен будет?
Плюс, для лучшей читаемости, даже если в цикле или ифе только одна строчка, хорошо бы все равно выделять фигурными скобками.

```
if (i == 0)
{
    DrawUpperBorderLine();
}
````

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                        Console.Write('║');
Аналогично, можно ли вынести это из цикла на уровень выше?

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                        Console.Write('║');
А это после цикла

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                    DrawLowerBorderLine();
Тоже самое, можно ли это вынести после цикла?

2020-01-06 23:04 UTC, Dronch commented on field.cs
>          }
Здесь мы лишний раз обходим все поле, как насчет того, чтобы делать это проверку во время рендеринга и бросать исключение? Останется обернуть вызов функции DrawField в try и ловить это иключение.

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                    int xNeighborPos = (xPos + j + _width) % -_width;
Не лишний ли здесь минус? Остаток от деления всегда положительный.

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +                    }
true - это единица, false - ноль
Как насчет того, чтобы использовать это:
`activeCells += Convert.ToInt32(_cells[yNeighborPos, xNeighborPos].IsActive);`

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +        }
1) В каждой из этих функций мы проходим через все элементы rows.
Можем ли мы вынести этот цикл за пределы функций и передавать каждой из них row?

2) Как насчет того, чтобы сделать кастомные исключения, чтобы их можно было потом удобно ловить в блоке try? https://www.tutorialsteacher.com/csharp/custom-exception-csharp
Предлагаю добавить их в отдельный файл exceptions.cs

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +            }
Можно ли более элегантно сделать строку из повторяющихся символов? Например так:
```
string horizontal_border = new String('═',  _width);
Console.Write(horizontal_border);
```

2020-01-06 23:04 UTC, Dronch commented on field.cs
> +            }
Копипаст кусков кода - это не очень хорошо. Предлагаю просто вынести это в отдельный метод DrawHorizontalBorderLine()

2020-01-07 10:15 UTC, kismetd commented on cell.cs
> +        }
Да. Начиная с 6# это распространенная практика для написания авто-свойств и конструкторов с одним аргументом. Исправил.

2020-01-07 10:48 UTC, kismetd commented on cell.cs
> +        }
Можно сделать так. Выйдет две bool, willBeBorn и willDie.
`bool willBeBorn = !IsActive && activeNeighbors == 3;`
`bool willDie = IsActive && (activeNeighbors < 2 || activeNeighbors > 3);`

Одной переменной не обойтись, т.к. простое !willBeBorn будет покрывать вообще все случаи, даже когда клетка не должна менять статус. При чтении if-ов все равно придется поднимать глаза к расшифровкам этих двух bool.

2020-01-07 10:55 UTC, kismetd commented on field.cs
> +            _height = height; //y (i)
Вообще, да. Это уберегло бы меня от того бага с игровой логикой. Приведу все к единому виду. Учитывая, что контекст кода подразумевает работу с игровым полем, обозначения осей как X и Y более чем уместны.

2020-01-07 13:45 UTC, Dronch commented on cell.cs
> +        }
Все верно, нужны 2 переменные. Для того кто первый раз читает код будет гораздо понятнее, если будет выглядеть как-то так 
```
Если родится, то ..., а если умрет, то ...
```
И да где-то вверху будет инициализация, но зато сразу будет понятно что это условие значит.
Если же загонять эти сложные выражения в ифы, то тот, кто читает первый раз увидит
```
Если длинное выражение, то ..., а если другое длинное выражение, то
```

Я бы провел аналогию с магическими числами. Где-то вверху они определены и не страшно.

2020-01-07 17:18 UTC, kismetd commented on field.cs
> +        }
1. Не могу придумать пока.

2020-01-08 19:33 UTC, merged