Some unit tests.
Dronch/GameLifeCSharpConsole pull request #3
Opened 2020-01-15 15:23 UTC by kismetd

Добавлено немного юнит тестов. Полного покрытия пока нет. Отправляю что есть, чтобы знать правильно ли тесты реализованы и имеют ли выбранные проверки логический смысл.

2020-01-16 07:57 UTC, Dronch requested changes
- Все что касается тестов круто было бы поместить в один каталог
- В файле NUnitTests.cs 2 тестовых класса, можно ли разбить на 2 файла, чтобы в каждом было по одному тестовому классу?
- Нэйминг функций мне скорее нравится, чем нет. Например WrongInputFieldHeight - понятно что происходит (хотя можно WrongInputFieldHeightThrowsException, но и как есть норм), а PredictCellStatusInputWillBeBorn не очень прозрачный тест. 
- Ход мысли у тебя правильный. Не нужно гнаться за полным покрытием. Давай доведем до ума те тесты, которые уже есть, этого будет достаточно.

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +        }
Обычно для того, чтобы получать экземпляр класса используют фабрику. В тестировании этот паттерн удобнее всего подходит. У меня обычно все фабрики в тестах в отдельном файле (Например если у нас не один файл NUnitTests.cs, а много разных тестов и везде нужны экземпляры этого класса).
```
// В конструктор передаем все что нужно, чтобы получить экземпляр, требуемый для конкретного теста
public class CellFactory
{
    public Cell create(bool active)
    {
        Cell instance = new Cell(active);
        instance.ChangeGeneration();
        return instance;
    }
}
```

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +        }
Ничего менять не будем, но как ты вчера и заметил, круто бы было, если бы метод ChangeGeneration возвращал значение _willBeActive, тогда не нужна была бы Cell.WillBeActive

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +        }
- Зачем нам переменная activeCells, мы ее здесь нигде не используем.
- Лучше разбить на два метода, например CellBecomesActiveAfterPredictGeneration и CellBecomesIncativeAfterPredictGeneration
- Условное выражение всегда дает нам булеву переменную, избыпочно проверять ее значение. Например:
```
bool valid = true;
if (valid == true) //  Не нужно так
if (valid) // збс
```
Соответственно, в нашем случае Assert.IsTrue((GetActiveCellSample().IsActive);

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +    }
Тоже самое, что и по предыдущему пункту. Я так полагаю, что здесь везде пропущен вызов Cell.PredictCellStatus(activeCells). Но в любом случае проверять переменную с которой ничего не происходит (даже если бы мы его вызывали) не нужно, соответственно проверки типа `activeCells < 2 || activeCells > 3` эквивалентны тому, что ты просто константы проверяешь `1 < 2 || 1 > 3`, их можно опустить.

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +        }
Мне нравится нэйминг и реализация, сразу понятно что к чему.

2020-01-16 07:57 UTC, Dronch commented on NUnitTests.cs
> +        }
Здесь происходит что-то плохое. Нам нужно ловить исключение NoActiveCellsException, а не инициализировать его здесь. Суть тестов в том, что тесты должны быть простые и понятные: вызвал функцию с какими-то заданными параметрами -> что-то произошло. Очевидно здесь нужно вызывать метод, который кинет нам исключение NoActiveCellsException (Field.DrawField).

2020-01-16 13:50 UTC, kismetd commented on NUnitTests.cs
> +        }
Здесь вышло странно. Поначалу и было сделано так: 
`Field field = new Field(20, 40, false);`
`string path = "inputAllZeroes.txt";`
`field.Init(path);`
`Assert.Throws<NoActiveCellsException>(() => field.DrawField());`

Но в результате при запуске этого теста я получаю:
`Message:       Expected: <GameLifeCSharpConsole.NoActiveCellsException>`
`But was:  <System.IO.IOException: Неверный дескриптор.`

Но при этом, в режиме дебаггинга исключение успешно выбрасывается и тест проходит:
![failedTest](https://user-images.githubusercontent.com/25157750/72530356-41417680-3880-11ea-86e8-88bbc9d58196.png)

2020-01-17 11:00 UTC, kismetd commented on NUnitTests.cs
> +        }
Проблема была в  Console.Clear(), вызывавшем IO.Exception.

2020-01-17 11:00 UTC, merged